name: Lint Code Style
on: push
jobs:
  Super-Linter:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code
        uses: github/super-linter@v3.13.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          # VALIDATE_YAML: true
          # VALIDATE_JSON: true
          # VALIDATE_XML: true
          # VALIDATE_MD: true
          # VALIDATE_BASH: true
          # VALIDATE_JAVASCRIPT_ES: true
          # VALIDATE_CSS: true
          # VALIDATE_HTML: true

